### ISSUE TITLE
Sample is crashing on Android 4.X

### ISSUE THREAD

**Issue by lucas34** [Iojjj/RoundedCornersBackgroundSpan#3]
```java
 java.lang.IndexOutOfBoundsException
   at android.graphics.Paint.measureText(Paint.java:1780)
   at com.github.iojjj.rcbs.RoundedCornersBackgroundSpan.drawBackground(RoundedCornersBackgroundSpan.java:104)
```

**Comment by Iojjj** [comment]
Hi @lucas34 ,

could you also post a code that you're using to display text so I can reproduce it and fix. 

Thanks

**Comment by lucas34** [comment]
I just run the sample app. 

It seems like it's actually due to the second paragraph. It cannot fit entirely on my screen. So when it calculate the last line that can fit, for some reason, the endIndex is smaller than startInText.

I manage to quick fix by changing the check line 100 to 
```java
if (endInText <= startInText) {
   continue;
}
```

I haven't went through to the code to find the root cause but this quick fix solved the issue and the display seems to be correct.

**Comment by Iojjj** [comment]
Fix pushed to `develop` branch. Once I found keys for publishing I'll upload a new version of library on maven and close this issue.
