### ISSUE TITLE
DrawBackground contains multiple problems

### ISSUE THREAD

**Issue by lucas34** [Iojjj/RoundedCornersBackgroundSpan#4]
Hi,

1.
In drawBackground the variables start and startInText will always have the same value.
Because line 94 you assign the start + trimmedLengthStart to the variable start.
So when you measure with p.measureText(text, start, startInText) the returned value is wrong
I managed to fix the issue by assigning line 94 to a new variable like "actualStart"

2.
I'm using max and min so when I assign the left value, I will avoid having negative value. If you don't do this, you won't have the rounded corner on the left.

#3 
I also added the fix in this code

This is my code
```java
int actualStart = start;
int actualEnd = end;

if (trimmedLength != part.length()) {
    final int trimmedLengthStart = getTrimmedLengthStart(part);
    final int trimmedLengthEnd = getTrimmedLengthEnd(part, trimmedLengthStart);
    actualStart = start + trimmedLengthStart;
    actualEnd = end - trimmedLengthEnd;
}
final int startInText = actualStart < backgroundHolder.mStart ? backgroundHolder.mStart : actualStart;
final int endInText = actualEnd > backgroundHolder.mEnd ? backgroundHolder.mEnd : actualEnd;
// skip empty parts
if (endInText <= startInText) {
    continue;
}

float l = Math.max(p.measureText(text, start, startInText) - mPadding, 0); // Left
float t = Math.max(top - mPadding, 0); // Top
float r = Math.min(l + p.measureText(text, startInText, endInText) + mPadding, right); // right
float b = Math.min(baseline + p.descent() + mPadding, bottom); // bottom

mRectangle.set(l, t, r, b);
mPaint.setColor(backgroundHolder.mBgColor);
c.drawRoundRect(mRectangle, mRadius, mRadius, mPaint);
```

**Comment by Iojjj** [comment]
Hi @lucas34,

1. I can't say that `start` and `startInText` variables will be the same. Only in cases when on single line you have only one rounded background. See the logs below:

```
start: 0, startInText: 0
start: 23, startInText: 23
start: 44, startInText: 44
start: 44, startInText: 56
start: 88, startInText: 88
start: 88, startInText: 113
start: 134, startInText: 134
start: 134, startInText: 160
start: 180, startInText: 180
start: 180, startInText: 222
start: 228, startInText: 228
start: 228, startInText: 241
start: 265, startInText: 265
start: 295, startInText: 295
start: 295, startInText: 312
start: 338, startInText: 338
start: 338, startInText: 360
start: 379, startInText: 379
```

`start` variable holds index of first non-space character in current line.
`startInText` variable holds index of first character of rounded background span in current line.

Please, explain more why do you think that returned value is wrong?

2. Do you have any troubles with negative values? Please, provide sample code that shows the issues you have.

**Comment by lucas34** [comment]
For the point #2 

I think it's my bad, I didn't had the shadow radius

**Comment by lucas34** [comment]
Btw did you removed the two builders and combine in only one ?
Because now I can only see "Builder" but the doc said 
"Builder for creating RoundedCornersBackgroundSpan by text parts."

**Comment by Iojjj** [comment]
@lucas34, yes, `TextPartsBuilder` became just `Builder`. `EntireTextBuilder` completely removed.
