### ISSUE TITLE
Incorrect measuring after apply span size

### ISSUE THREAD

**Issue by iljaosintsev** [Iojjj/RoundedCornersBackgroundSpan#6]
Hi, thanks for great library. 
My use case more difficult than example. I using RoundedCornersBackgroundSpan and SizeSpan at the same time. But Paint object does not define new text size and background not change. Proof below.
![bug](https://cloud.githubusercontent.com/assets/3526847/25505984/bb090960-2bbd-11e7-81d6-79a8515a56ad.jpg)
```java
for (int i = 0; i < parts.length; i++) {
 final String part = parts[i];
 final String color = colors[i];
 final SpannableString string = new SpannableString(part);
 if (i == 3) {
  string.setSpan(new RelativeSizeSpan(1.5 f), 0, string.length(), Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);
 }
 if (!TextUtils.isEmpty(color)) {
  final ForegroundColorSpan colorSpan = new ForegroundColorSpan(Color.WHITE);
  string.setSpan(colorSpan, 0, string.length(), Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);
  textPartsBuilder.addTextPart(string, Color.parseColor(color));
 } else {
  textPartsBuilder.addTextPart(part);
 }
}
```

**Comment by Iojjj** [comment]
Hi @iljaosintsev,

I've fixed this in `develop` branch, you can pull latest code from there. I'll update the library on maven once I found keys for publishing and then will close this issue :)

![screenshot_1493397438](https://cloud.githubusercontent.com/assets/3605857/25538471/807b8a32-2c4b-11e7-95d2-8d8e6e247179.png)
