### ISSUE TITLE
Span position by TextAlignment setting.

### ISSUE THREAD

**Issue by yeonsik** [Iojjj/RoundedCornersBackgroundSpan#8]
Hi, thanks for great library. this is very useful for me.
I found a problem while using this library.
If I set the Text Alignment option to center in TextView, the Span position does not match.

![roundedcornersbackgroundspan](https://cloud.githubusercontent.com/assets/485222/26029926/2218aa54-387d-11e7-9378-91df5269a73a.jpg)

**Comment by Iojjj** [comment]
fixed. Because `Span` can't get info about text alignment from `TextView` you need to set text alignment with builder manually, for example:

```JAVA
final Spannable spanned = new RoundedCornersBackgroundSpan.Builder(this)
     ...
    .setTextAlignment(RoundedCornersBackgroundSpan.ALIGN_CENTER)
     ...
    .build();
```

![image](https://cloud.githubusercontent.com/assets/3605857/26107714/d8bdd3ac-3a52-11e7-8c77-a0b3fc5f13e4.png)

**Comment by yeonsik** [comment]
I updated.
perfect.
thanks.
